"""add_exclude_terms_to_search_profiles

Revision ID: 7c9c3a07f2c5
Revises: d6791cf9154a
Create Date: 2026-03-16 21:40:50.459812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9c3a07f2c5'
down_revision: Union[str, Sequence[str], None] = 'd6791cf9154a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('exclude_terms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'exclude_terms')
    # ### end Alembic commands ###
