"""add event date columns and pipeline_custom_dates table

Revision ID: 92cc6b5d5ecf
Revises: b89f7a3cc2f4
Create Date: 2026-03-25 18:28:57.240820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cc6b5d5ecf'
down_revision: Union[str, Sequence[str], None] = 'b89f7a3cc2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_custom_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_entry_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_entry_id'], ['pipeline_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('pipeline_comments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('pipeline_comments', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('pipeline_entries', sa.Column('applied_date', sa.Date(), nullable=True))
    op.add_column('pipeline_entries', sa.Column('recruiter_screen_date', sa.Date(), nullable=True))
    op.add_column('pipeline_entries', sa.Column('tech_screen_date', sa.Date(), nullable=True))
    op.add_column('pipeline_entries', sa.Column('onsite_date', sa.Date(), nullable=True))
    op.add_column('pipeline_entries', sa.Column('offer_date', sa.Date(), nullable=True))
    op.add_column('pipeline_entries', sa.Column('offer_expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_entries', 'offer_expiration_date')
    op.drop_column('pipeline_entries', 'offer_date')
    op.drop_column('pipeline_entries', 'onsite_date')
    op.drop_column('pipeline_entries', 'tech_screen_date')
    op.drop_column('pipeline_entries', 'recruiter_screen_date')
    op.drop_column('pipeline_entries', 'applied_date')
    op.alter_column('pipeline_comments', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('pipeline_comments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_table('pipeline_custom_dates')
    # ### end Alembic commands ###
